"""Syllabus configs for the ten CHART gap courses (spliced into build-syllabi.py)."""

B = "https://me5231979.github.io/Course_Library/courses"

def _c(slug, repo, title, subtitle, audience, core, skills, description,
       objectives, topics, activities, outcomes, frameworks, takelabel, voyage=False):
    aud = ("Part of the Manager Voyage program. " + audience) if voyage else audience
    return {
        "slug": slug,
        "coreSkills": core,
        "skills": skills,
        "title": title,
        "subtitle": subtitle,
        "audience": aud,
        "length": "Classroom: 90 minutes (60-minute core path). Self-paced web edition: about 45 minutes",
        "format": "Instructor-led, in person or virtual; learners join on their own devices via QR code. Private by design: exercises use roles and workflows (never names) and nothing typed is saved or transmitted",
        "group": "8 to 24 works best for the pair drills; scales larger with room votes",
        "description": description,
        "objectives": objectives,
        "topics": topics,
        "activities": activities,
        "outcomes": outcomes,
        "takehomes": [
            ("Printable cheat sheet", f"{B}/{repo}/cheatsheet.html"),
            (takelabel, f"{B}/{repo}/worksheet.html"),
            ("Self-paced web edition", f"{B}/{repo}/web/"),
        ],
        "learner": f"{B}/{repo}/",
        "facilitator": f"{B}/{repo}/facilitator/",
        "selfpaced": f"{B}/{repo}/web/",
        "frameworks": frameworks,
    }

KIRK = ("Built on Bloom's-verb objectives and instrumented with Kirkpatrick levels 1 to 3: a fist-to-five "
        "confidence check at close, a scored recap and per-section validation checks in session, and a "
        "capstone commitment card followed by a 7-day pulse and a 30-day re-poll. The facilitator edition "
        "follows an ATD runbook structure (Say, Do, Ask, Debrief, Transition) with Full 90 and Core 60 "
        "timed paths. Data rules follow Vanderbilt's approved-tool guidance and the shared traffic light: "
        "green for public or generic, yellow for internal work in approved VU tools only "
        "(ChatGPT EDU, Amplify, Copilot), red for private information about people, never.")

GAP_COURSES = [

_c("numbers-faster", "Numbers-Faster", "Numbers, Faster",
   "Data and analysis with AI, with the checking built in",
   "All Vanderbilt staff who touch a spreadsheet, a report, or a dashboard",
   ['Embodies an entrepreneurial spirit and leverages data and technology', 'Continuously strives for excellence'],
   ['Data Analysis', 'Artificial Intelligence', 'Data Storytelling'],
   "Vanderbilt runs on spreadsheets, Oracle reports, and end-of-month numbers, and most of that analysis is still done by hand. Gallup's workplace research puts data and analytics among the highest-payoff AI use cases, with roughly three in four users reporting clear productivity gains and one of the widest gaps between frequent and occasional users. This session teaches the Data Loop, four moves that make AI genuinely useful on real data: describe the file before asking anything, ask in a ladder from summary to comparison to outlier, check by recomputing the numbers that matter, and tell the finding in two plain sentences. A full section is spent on getting data safely into a tool, because a spreadsheet with names in it is red-light data no matter how useful the analysis would be. Learners work a realistic month-end analysis in the graded Analysis Lab, where the failure modes are the ones that actually happen: the total that never matched the row count, the retracted number, the privacy near-miss.",
   ["Explain where AI genuinely helps with data work and where it fails",
    "Prepare a dataset safely for AI, applying the traffic light to files as well as questions",
    "Apply the Data Loop to interrogate a real spreadsheet",
    "Build a comparison and a chart brief with AI",
    "Verify AI-produced numbers before they travel to anyone else"],
   [("The case", "Where data work sits among AI use cases, and the specific ways AI gets numbers wrong: dropped rows, invented categories, confident bad math"),
    ("Safe data in", "The traffic light applied to files: published data, internal aggregates, and anything identifying a person, plus practical de-identification"),
    ("Ask the sheet", "Describe the columns before the first question, then the question ladder from summary to comparison to outlier to explanation"),
    ("Check the math", "Recompute one figure by hand, reconcile totals and counts, trace surprising claims back to rows"),
    ("The Analysis Lab", "A graded month-end analysis: prepare, ask, check, and tell, with outcomes at week four"),
    ("Tell the story", "The two-sentence finding, chart briefs that specify the comparison and the takeaway, and the one thing never to outsource: the recommendation")],
   "Four scenario trainers (a research guessing game, a green-yellow-red file sort, a catch-the-error drill, and a judge-the-finding drill), a private data mapper that turns a learner's real dataset into a Data Loop starter, the graded Analysis Lab with rerun, inline knowledge checks, a scored recap, and the My Data Loop Card capstone.",
   "Learners leave with a dated card naming one real dataset, the first Data Loop move they will run on it, the check ritual they commit to, and a metric (minutes to answer, compared with before). Learning is measured in session through trainer scores, the graded lab, and a recap mapped to the objectives; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse on analyses actually run and numbers actually caught.",
   KIRK, "Data Loop card"),

_c("ai-guardrails", "AI-Guardrails", "Guardrails & Responsible Use",
   "The four things every team needs written down",
   "All Vanderbilt staff using AI for university work, and the managers who set the rules",
   ['Makes effective and ethical decisions for the University', 'Embodies an entrepreneurial spirit and leverages data and technology'],
   ['Responsible AI', 'Data Privacy', 'Risk Management'],
   "Start Smarter taught the traffic light for what is safe to paste. This session is the standalone governance course that writes down the rest. Stanford's AI Index tracks AI misuse incidents climbing in step with adoption, and at a university holding FERPA-protected student records and health-adjacent data, being careful is a habit rather than a policy. Learners build the Four Lines, a one-page working agreement any team can adopt: what data may go into which tools, when a human must verify before something travels, when readers must be told AI helped, and who owns the output when it is wrong. Each line gets its own drill on the hard cases rather than the easy ones: student work, meeting notes naming colleagues, recommendation letters, grant drafts, the rejection email that mentions a person by name. The session ends with learners drafting the first two lines for their own team.",
   ["Explain why written guardrails protect a team in ways good intentions cannot once AI use scales",
    "Classify data with the traffic light, including the hard cases: student work, meeting notes, letters about people",
    "Decide which outputs need a named human check and when AI use must be disclosed to the reader",
    "Assign ownership of every AI-assisted output to the human who ships it",
    "Draft the Four Lines, a starter one-page agreement for your own team's real work"],
   [("Why written rules", "Incidents rising alongside adoption, and the difference between a team with written lines and a team with assumptions"),
    ("Line one: what goes in", "The traffic light with its hard cases, and why anything about a person stays out of unapproved tools"),
    ("Line two: when a human verifies", "Sizing the check to what the output can break, from no check at all to a full source check"),
    ("Line three: when we disclose", "The would-they-feel-misled test, applied to external communications, assessment, and the university's voice"),
    ("Line four: who owns it", "Output ownership, the unread-draft problem, and why AI never appears in an accountability chain"),
    ("Write your Four Lines", "Drafting the agreement, giving it a home people can find, and routing genuinely unclear cases to policy owners")],
   "Four scenario trainers (a research guessing game, a hard-case traffic-light sort, a size-the-check triage, and a disclose-or-not drill), a private agreement drafter that produces a starter Four Lines, the graded Guardrails Lab following a rollout to month one, inline knowledge checks, a scored recap, and the capstone commitment card.",
   "Learners leave with a drafted agreement covering their own team's real work, a named home for it, and a dated first move to bring it to the team. Learning is measured in session through trainer scores, the graded lab, and a scored recap; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse on agreements actually discussed and a 30-day re-poll on whether the lines survived contact with real work.",
   KIRK, "Four Lines agreement"),

_c("trust-then-verify", "Trust-Then-Verify", "Trust, Then Verify",
   "Verifying AI output and reviewing it critically",
   "All Vanderbilt staff who use AI output in work that reaches anyone else",
   ['Continuously strives for excellence', 'Makes effective and ethical decisions for the University'],
   ['Critical Thinking', 'Artificial Intelligence', 'Fact-Checking'],
   "Answers, Faster taught ask, anchor, check for research questions. This session teaches the broader skill as its own discipline, because AI errors do not arrive looking like errors: they arrive fluent, specific, and confident. SHRM finds workers losing meaningful hours every week to fixing AI output they trusted too quickly, which makes verification a trainable skill with a measurable payoff. The method is the Three Reads: the claim read that underlines every checkable assertion, the source read that traces the riskiest ones to something trustworthy, and the slant read that asks what the output assumes and who is missing from it. Around that sits a failure taxonomy (hallucination, staleness, slant, omission, and faked math, each with its own tell), verification budgets sized to what the output can break, and the stop rules for when a task should leave AI entirely.",
   ["Recognize how AI errors actually present themselves: fluent, specific, and wrong",
    "Apply the Three Reads to any AI output: the claim read, the source read, and the slant read",
    "Distinguish hallucination, staleness, slant, omission, and faked math by their tells",
    "Size verification to the stakes, from no check at all to expert review",
    "Decide when to stop using AI for a task altogether"],
   [("The cost of belief", "Why fluency fools careful people, and the weekly cleanup tax the research keeps measuring"),
    ("Know the failure modes", "The taxonomy with a one-line tell for each, practiced on real-looking outputs"),
    ("The Three Reads", "The method worked end to end on a policy summary carrying an invented deadline, a stale figure, and a slanted frame"),
    ("Size the check", "Verification budgets, the stakes ladder, and the stop rules"),
    ("The Verification Lab", "A graded hour-to-deadline briefing: what you check, the citation you cannot find, and how you sign it off"),
    ("Make it a habit", "The 90-second daily version, the no-blame miss log, and treating bias review as everyone's job")],
   "Four scenario trainers (a research guessing game, a name-the-failure drill, a find-the-fault-line drill, and a check-ship-or-stop triage), a private ritual builder that turns a learner's most-trusted output into a 90-second check, the graded Verification Lab with rerun, inline knowledge checks, a scored recap, and the My Verification Card capstone.",
   "Learners leave with a dated card naming the recurring AI output they will verify, the fault lines in it, and the 90-second ritual they commit to. Learning is measured in session through trainer scores, the graded lab, and a recap mapped to the objectives; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse asking what the checks caught.",
   KIRK, "verification card"),

_c("admin-automated", "Admin-Automated", "Admin, Automated",
   "Personal automation and getting repetitive work off your plate",
   "All Vanderbilt staff whose week is full of email, calendars, and recurring reports",
   ['Embodies an entrepreneurial spirit and leverages data and technology', 'Continuously strives for excellence'],
   ['Personal Productivity', 'Artificial Intelligence', 'Process Improvement'],
   "Gallup finds automating repetitive tasks the single highest-payoff AI use case, with around 77 percent of users reporting clear productivity gains. It is also the use case where the gains most reliably vanish, because saved time that nobody named gets absorbed into more meetings. This session runs the Repeat Audit: spot the work you have done the same way more than twice, template it with real slots instead of last month's leftovers, route what arrives using a three-pile triage you stay accountable for, and retire the recurring obligations that should simply stop. Email triage, calendar rules, and the monthly report cycle all get worked directly. The session closes by banking the recovered hours on purpose, because a gain nobody named is a gain nobody keeps.",
   ["Identify the repetitive layer inside a real working week",
    "Build reusable templates with AI for recurring messages and reports",
    "Set up AI-assisted email triage that you remain accountable for",
    "Apply calendar rules that defend focus time",
    "Decide which recurring work to retire entirely, and bank the hours you recover"],
   [("The repeat tax", "How much of an ordinary week is repetition rather than work, and what the research says about automating it"),
    ("Spot it", "The recurrence inventory and its tells: searching for an old email to copy, rebuilding the same table monthly"),
    ("Template it", "Building the skeleton from de-identified examples, keeping your voice, and template hygiene so no name is ever left behind"),
    ("Route it", "The three-pile triage, AI-drafted routine replies you read before sending, and calendar rules including the decline template"),
    ("The Automation Lab", "A graded rebuild of the monthly report cycle, from gathering inputs to the send"),
    ("Retire it and bank it", "Testing retirement safely with your manager in the loop, then naming where the recovered hours go")],
   "Four scenario trainers (a research guessing game, a judge-the-template drill, an inbox triage drill, and a keep-shrink-or-retire sort), a private repeat inventory that ranks a learner's own automation candidates, the graded Automation Lab with rerun, inline knowledge checks, a scored recap, and the My Repeat Audit Card capstone.",
   "Learners leave with a dated card naming one repetitive task, the automation move they will make, the failure mode they are avoiding, and an explicit destination for the time they recover. Learning is measured in session through trainer scores, the graded lab, and a scored recap; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse on what was automated and where the hours went.",
   KIRK, "Repeat Audit card"),

_c("ai-across-your-week", "AI-Across-Your-Week", "Across Your Week",
   "The CHART integrator: five assists on one real week",
   "Vanderbilt staff who have taken at least one or two CHART courses and want the habit rather than the trick",
   ['Embodies an entrepreneurial spirit and leverages data and technology', 'Continuously strives for excellence'],
   ['Artificial Intelligence', 'Workflow Design', 'Time Management'],
   "Gallup's most striking AI finding is about breadth rather than depth: people using AI across seven or more distinct tasks are roughly twice as likely to report real productivity gains as people using it for one or two. Every other CHART course is an excellent single-use-case builder, and this one is the capstone that strings them together. Learners inventory their actual week into recurring blocks, match each block to a CHART method by its verb rather than its topic, stack two methods on a single task so the output of one becomes the input of the next, and then confront the finding that decides whether any of it lasts: saved time evaporates into more meetings unless it is deliberately banked. The graded Week Lab runs Monday to Friday for a program coordinator, and every choice in it is one the learner will make on their own calendar.",
   ["Explain why breadth of use predicts productivity gains better than intensity",
    "Inventory a real week into blocks that can be matched to AI methods",
    "Match each block to the right CHART method by its verb",
    "Stack two methods on a single task while keeping each link's check",
    "Commit to a five-assist week with the reclaimed time visibly banked"],
   [("The breadth effect", "Why the one-trick user plateaus, and what separates them from the seven-plus user"),
    ("The inventory", "Seeing a week as blocks, costing each one honestly, and keeping the inventory to roles and workflows"),
    ("The method match", "The CHART toolbox on one page, matched by verb: writing, questioning, deciding, condensing, analyzing"),
    ("The stack", "Chaining methods so one output feeds the next, and why a chain is only as trustworthy as its weakest check"),
    ("The Week Lab", "A graded Monday-to-Friday plan with outcomes at week four"),
    ("Bank the time", "Naming the destination for reclaimed hours before they disappear into the calendar")],
   "Four scenario trainers (a research guessing game, a match-the-method drill, a build-the-chain drill, and a judge-the-bank drill), a private week inventory that surfaces a learner's own redesign candidates, the graded Week Lab with rerun, inline knowledge checks, a scored recap, and the My Week Map capstone.",
   "Learners leave with a Week Map naming five blocks, the first method stack they will run, the failure mode they are avoiding, and a named destination for the hours they reclaim. Learning is measured in session through trainer scores, the graded lab, and a recap mapped to the objectives; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse counting assists actually run and a 30-day re-poll on where the time went.",
   KIRK, "Week Map"),

_c("people-data-with-ai", "People-Data-with-AI", "People Data, Safely",
   "Read the patterns, coach the person",
   "Managers and team leads who receive engagement results, keep 1:1 notes, or write performance feedback",
   ['Grows self and others', 'Makes effective and ethical decisions for the University'],
   ['People Analytics', 'Coaching Techniques', 'Artificial Intelligence'],
   "Coaching for Performance taught the human method, and Decisions, Sharper handles judgment calls. This session teaches the people-data side, inside hard privacy lines. Culture Amp, Lattice, and 15Five are all pushing managers toward AI-assisted people insight, which makes the governing skill the ability to find patterns without ever putting a person into a tool. The spine is the Aggregate Rule: an individual is red-light data always, aggregated and de-identified team data is yellow and belongs only in approved VU tools, and published benchmarks are green. The small-team trap gets named directly, because a team-level number from a team of three identifies people. On top of that sits the Coach's Loop: aggregate, interrogate, humanize by testing every AI theme against what you actually know, and then converse, because people data that never becomes a conversation was just a dashboard.",
   ["Apply the Aggregate Rule to every people-data case, including the small-team trap",
    "Use AI to find themes in engagement results and meeting notes at team level only",
    "Draft feedback with AI as a rehearsal partner, never as a verdict",
    "Prepare a review cycle by structuring your own evidence rather than generating judgments",
    "Run the follow-up conversation the data existed to produce"],
   [("The new expectation", "The HR-tech wave putting AI coaches in front of managers, and the gap where survey results produce no behavior change"),
    ("The Aggregate Rule", "The traffic light applied to people data, with the small-team trap and the 1:1 notes case"),
    ("Themes from the noise", "Interrogating aggregated results, and the ground-truth test that separates a finding from a hypothesis"),
    ("Feedback, rehearsed", "AI as rehearsal partner using roles instead of names, and the line it never crosses"),
    ("The Review Prep Lab", "A graded review season for a team of eight: evidence, drafting, calibration, and delivery prep"),
    ("From data to conversation", "Sharing themes back, building the 1:1 question bank, and measuring conversations rather than dashboard views")],
   "Four scenario trainers (a research guessing game, a red-yellow-green people-data sort including the small-team trap, a judge-the-draft feedback drill, and a judge-the-share-back drill), a private interrogation planner, the graded Review Prep Lab with rerun, inline knowledge checks, a scored recap, and the My People-Data Card capstone.",
   "Learners leave with a dated card naming the people-data source they will work, the aggregation step that makes it safe, the three questions they will ask, and the conversation they have scheduled. Learning is measured in session through trainer scores, the graded lab, and a scored recap; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse on conversations actually held.",
   KIRK, "people-data card", voyage=True),

_c("making-ai-normal", "Leading-AI-Adoption", "Making It Normal",
   "Modeling, norms, and leading adoption on your team",
   "Managers and team leads responsible for whether their team actually uses AI",
   ['Leads and inspires teams', 'Radically collaborates and cultivates belonging'],
   ['Change Management', 'Artificial Intelligence', 'Team Development'],
   "This is the 90-minute companion to the short Leading the Shift course, for managers who want the full method and the facilitator runbook. Gallup names manager modeling and workflow integration the two strongest predictors of frequent AI use on a team, ahead of tooling, licenses, and mandates, and most employees report that nobody ever told them what is actually encouraged. Workflow and Process Redesign covers the mechanics of changing how work flows; this session covers the behavior around it. The method is Show, Say, Set, Sustain: narrate your own use including the misses so that using AI imperfectly in public is safe, give explicit permission and explicit limits because silence reads as prohibition to half a team and as a free-for-all to the other half, install AI into the rituals where habits actually live, and hold the practice past the month-three novelty cliff when workload returns and usage quietly dips.",
   ["Explain why manager modeling and workflow integration predict team AI use better than tools or mandates",
    "Model AI use visibly, including the checks and the misses",
    "Give a team explicit permission and explicit limits",
    "Install AI norms into 1:1s and team meetings, with the psychological safety that makes them work",
    "Sustain adoption past the novelty cliff with protected learning time and honest measurement"],
   [("The modeling effect", "What actually predicts team AI use, and the permission gap sitting inside most teams"),
    ("Show: model out loud", "Narrated use, modeling the check rather than the speed, and making public fumbles safe"),
    ("Say: permission and limits", "The encouraged list, the never list, and who to ask when a case is unclear"),
    ("Set: norms in the rituals", "The 1:1 question, the share-one round, the no-blame miss log, and pairing the skeptic with the enthusiast"),
    ("The Adoption Lab", "A graded 90 days of leading a six-person team's adoption"),
    ("Sustain past the novelty cliff", "Protected learning time, celebrating caught errors, and reporting adoption as stories rather than surveillance")],
   "Four scenario trainers (a research guessing game, a judge-the-model drill, a fix-the-ritual drill, and a month-three moves drill), a private permission-talk builder, the graded Adoption Lab with rerun, inline knowledge checks, a scored recap, and the capstone adoption plan.",
   "Learners leave with a dated plan naming their team's current AI temperature, the first visible move they will make, the failure mode they are avoiding, and the ritual they are installing. Learning is measured in session through trainer scores, the graded lab, and a recap mapped to the objectives; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse and a 30-day re-poll on whether the ritual survived.",
   KIRK, "adoption plan", voyage=True),

_c("delegating-with-ai", "Delegating-with-AI", "Delegating, Rethought",
   "Routing work without hollowing out your team",
   "Managers and team leads who assign work and grow the people doing it",
   ['Grows self and others', 'Leads and inspires teams'],
   ['Delegation', 'Role Design', 'Artificial Intelligence'],
   "The same task can now go to AI, to a junior team member as a stretch assignment, or stay with you, and nobody trained managers for that choice. Route everything routine to the machine and you hollow out the apprenticeship your juniors learn by, since yesterday's growth work (first drafts, research passes, the summary nobody enjoyed) is exactly today's AI lane. Route nothing and you spend your team's hours on transcription. Stanford GSB frames the shift as leaders needing to redesign roles and processes rather than simply oversee execution. This session teaches the Routing Test in a deliberate order, growth first, then judgment, then volume, because the growth question is the one AI-era managers forget. It then teaches role math: rebuilding a job around judgment reps, verification ownership, and human contact as the routine layer drains away.",
   ["Apply the Routing Test to real tasks: the growth question, the judgment question, the volume question",
    "Distinguish stretch work from grunt work before routing either",
    "Keep the apprenticeship pipeline alive as AI absorbs routine tasks",
    "Redesign a role rather than just a task list",
    "Brief a delegation, to a person or to AI, so it lands with clear checks"],
   [("The new triage", "Three destinations, and why default-to-AI and default-to-people both fail"),
    ("The Routing Test", "The three questions in order, with the tells that separate them"),
    ("Stretch versus grunt", "The distinction that decides careers, and the honest problem of building new stretch when the old kind is automated"),
    ("Role math", "What backfills a role as routine drains, and how to have that conversation with the person in it"),
    ("The Routing Lab", "A graded quarter: four tasks arrive at once and every routing has consequences"),
    ("The handoff", "Briefing a delegation both ways, and why a delegation to AI is really a delegation to the verifier")],
   "Four scenario trainers (a research guessing game, a route-the-task drill, a stretch-or-grunt drill, and a judge-the-handoff drill), a private role-math sketch for a real role on the learner's team, the graded Routing Lab with rerun, inline knowledge checks, a scored recap, and the My Routing Card capstone.",
   "Learners leave with a dated card naming a task they have been holding, its destination, the handoff brief, and the growth they are protecting. Learning is measured in session through trainer scores, the graded lab, and a scored recap; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse on routings actually made and what the receiving person learned.",
   KIRK, "routing card", voyage=True),

_c("hiring-with-ai", "Hiring-with-AI", "Hiring, Human",
   "Fair, useful, and inside the lines",
   "Managers and team leads who hire, interview, or make talent decisions",
   ['Makes effective and ethical decisions for the University', 'Grows self and others'],
   ['Structured Interviewing', 'Talent Management', 'Responsible AI'],
   "Pasting a resume into a chatbot feels efficient and is a violation: candidate materials are private information about people, and AI never ranks, screens, or scores a human being. This session draws that line hard and then teaches everything genuinely valuable on the right side of it, which turns out to be most of the value anyway. Structure is the most evidence-backed fairness tool in hiring, and AI is excellent at building structure and terrible at judging people. Learners use it to audit job postings for proxy requirements that quietly shrink the pool, generate behavioral questions from a role's real tasks, draft scoring anchors before a single application is read, and map the skills a team actually lacks. A full section covers where bias enters even the legitimate uses, including culture fit as a laundromat for preference, and when HR and university policy must be involved.",
   ["Classify hiring materials with the traffic light and defend the red line",
    "Use AI to draft inclusive job descriptions and audit requirements for proxies",
    "Build a scoring rubric with anchors before seeing any candidates",
    "Run a skills map for your team's real gaps",
    "Recognize where bias enters AI-assisted hiring and apply the guardrails that catch it"],
   [("The temptation and the line", "Why the obvious use is the forbidden one, across privacy, fairness, and regulated employment decisions"),
    ("The red side, exactly", "The full never list, including reference summaries, interview notes, and the rejection email that names a person"),
    ("The wide funnel", "Auditing postings for proxy requirements, degree inflation, and jargon, plus skills mapping before the post is written"),
    ("Structure before candidates", "The structure dividend, behavioral questions from real tasks, and anchors written before applications arrive"),
    ("The Hiring Lab", "A graded search from posting to decision, with the privacy violation among the possible outcomes"),
    ("Bias, watched", "Where bias enters legitimate uses, the same-evidence test, and when HR must be in the room")],
   "Four scenario trainers (a research guessing game, an over-the-line classification drill, a fix-the-posting drill, and a spot-the-bias-door drill), a private structure planner producing question seeds and a rubric skeleton, the graded Hiring Lab with rerun, inline knowledge checks, a scored recap, and the My Hiring Structure Card capstone.",
   "Learners leave with a dated card naming the role or talent decision in front of them, the structure they will build before seeing candidates, and an explicit red-line pledge. Learning is measured in session through trainer scores, the graded lab, and a recap mapped to the objectives; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse on rubrics built before applications were read.",
   KIRK, "hiring structure card", voyage=True),

_c("change-leadership-for-ai", "Change-Leadership-for-AI", "Change That Sticks",
   "Naming fear, building safety, leading the conversation",
   "Managers and team leads guiding a team through AI-driven change",
   ['Leads and inspires teams', 'Develops and implements University strategy'],
   ['Change Management', 'Psychological Safety', 'Communication Strategies'],
   "Workflow and Process Redesign tags change management; this session makes change leadership the entire subject. Accenture finds only about 18 percent of leaders lead AI investments effectively, and the differentiators are curiosity, courage, and connection rather than tool fluency. AI change fails on human ground: it gets announced as technology and experienced as threat, and the unnamed question in the room converts quietly into resistance. The method is Name, Frame, Invite, Hold: say the fear out loud before it says itself, frame honestly including what you do not know and never promising what you cannot deliver, invite the team into the design because people support what they help build, and hold the container over months rather than declaring victory at the announcement. The session pairs naturally with the Building Brave Teams workshop.",
   ["Explain why AI change fails on human ground rather than technical ground",
    "Name fear and job-security concerns directly, without false promises",
    "Build psychological safety around experimenting with AI in public",
    "Facilitate your team's own ethics and governance conversation",
    "Sustain change leadership over months rather than announcements"],
   [("Why AI change fails", "The Accenture finding, and the pattern of change announced as technology and experienced as threat"),
    ("Name the fear", "The unsaid question in every AI meeting, with scripts and the honesty rules that keep them credible"),
    ("Safety to stumble", "Psychological safety applied to adoption, and why the quiet ones rather than the enthusiasts decide whether change sticks"),
    ("The ethics conversation", "Hosting it rather than outsourcing it, treating disagreement as material, and knowing when to escalate"),
    ("The Change Lab", "A graded six months, including the job-security question asked point blank in week two"),
    ("Hold for the long arc", "The revisit cadence, the quiet signals worth watching, and measuring trust rather than usage")],
   "Four scenario trainers (a research guessing game, a judge-the-opening-line drill, a read-the-room drill, and a long-arc moves drill), a private conversation planner producing a naming line and a first ethics agenda, the graded Change Lab with rerun, inline knowledge checks, a scored recap, and the My Change Card capstone.",
   "Learners leave with a dated card naming the change their team faces, the naming line they will use, the honest frame, the invitation, and a revisit date. Learning is measured in session through trainer scores, the graded lab, and a scored recap; at close through a confidence check and a spoken commitment; and afterward through a 7-day pulse on conversations actually held and a 30-day re-poll on trust rather than usage.",
   KIRK, "change card", voyage=True),
]
